language: bash

services:
  - docker

before_install:
  - docker pull registry.fedoraproject.org/fedora-minimal:28
  - docker build -t tabit/qwt .
  - mkdir -p qwtiso

script:
  - docker run -v $(pwd):/src -v qwtiso:/build/noarch -it tabit/qwt sh -c "sh prep.sh && make x64 && rpmbuild -bb --define '_sourcedir /build' --define '_rpmdir /build' *.spec && cd noarch && createrepo ./"
