language: bash

if: tag IS present

services:
  - docker

before_install:
  - docker build -t tabit/qwt .
  - mkdir -p qwtiso

script:
  - docker run -v $(pwd):/src -v qwtiso:/build/noarch -it tabit/qwt sh -c "sh prep.sh && make x86 && make x64 && rpmbuild -bb --define '_sourcedir /build' --define '_rpmdir /build' *.spec && cd noarch && createrepo ./"
